import type { LegacyEnvSpec } from './config-env-shared.js';

export const GLOBAL_LEGACY_ENV_SPECS: readonly LegacyEnvSpec[] = [
  {
    env: 'TAKT_INTERACTIVE_PREVIEW_MOVEMENTS',
    path: 'interactive_preview_movements',
    type: 'number',
    blockedBy: [],
    warning: 'Deprecated: "TAKT_INTERACTIVE_PREVIEW_MOVEMENTS" is deprecated. Use "TAKT_INTERACTIVE_PREVIEW_STEPS" instead.',
  },
  {
    env: 'TAKT_ENABLE_BUILTIN_PIECES',
    path: 'enable_builtin_pieces',
    type: 'boolean',
    blockedBy: ['TAKT_ENABLE_BUILTIN_WORKFLOWS'],
    warning: 'Deprecated: "TAKT_ENABLE_BUILTIN_PIECES" is deprecated. Use "TAKT_ENABLE_BUILTIN_WORKFLOWS" instead.',
  },
  {
    env: 'TAKT_PIECE_CATEGORIES_FILE',
    path: 'piece_categories_file',
    type: 'string',
    blockedBy: ['TAKT_WORKFLOW_CATEGORIES_FILE'],
    warning: 'Deprecated: "TAKT_PIECE_CATEGORIES_FILE" is deprecated. Use "TAKT_WORKFLOW_CATEGORIES_FILE" instead.',
  },
  {
    env: 'TAKT_PIECE_RUNTIME_PREPARE',
    path: 'piece_runtime_prepare',
    type: 'json',
    blockedBy: ['TAKT_WORKFLOW_RUNTIME_PREPARE'],
    warning: 'Deprecated: "TAKT_PIECE_RUNTIME_PREPARE" is deprecated. Use "TAKT_WORKFLOW_RUNTIME_PREPARE" instead.',
  },
  {
    env: 'TAKT_PIECE_RUNTIME_PREPARE_CUSTOM_SCRIPTS',
    path: 'piece_runtime_prepare.custom_scripts',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_RUNTIME_PREPARE', 'TAKT_WORKFLOW_RUNTIME_PREPARE_CUSTOM_SCRIPTS'],
    warning: 'Deprecated: "TAKT_PIECE_RUNTIME_PREPARE_CUSTOM_SCRIPTS" is deprecated. Use "TAKT_WORKFLOW_RUNTIME_PREPARE_CUSTOM_SCRIPTS" instead.',
  },
  {
    env: 'TAKT_PIECE_ARPEGGIO',
    path: 'piece_arpeggio',
    type: 'json',
    blockedBy: ['TAKT_WORKFLOW_ARPEGGIO'],
    warning: 'Deprecated: "TAKT_PIECE_ARPEGGIO" is deprecated. Use "TAKT_WORKFLOW_ARPEGGIO" instead.',
  },
  {
    env: 'TAKT_PIECE_ARPEGGIO_CUSTOM_DATA_SOURCE_MODULES',
    path: 'piece_arpeggio.custom_data_source_modules',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_ARPEGGIO', 'TAKT_WORKFLOW_ARPEGGIO_CUSTOM_DATA_SOURCE_MODULES'],
    warning: 'Deprecated: "TAKT_PIECE_ARPEGGIO_CUSTOM_DATA_SOURCE_MODULES" is deprecated. Use "TAKT_WORKFLOW_ARPEGGIO_CUSTOM_DATA_SOURCE_MODULES" instead.',
  },
  {
    env: 'TAKT_PIECE_ARPEGGIO_CUSTOM_MERGE_INLINE_JS',
    path: 'piece_arpeggio.custom_merge_inline_js',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_ARPEGGIO', 'TAKT_WORKFLOW_ARPEGGIO_CUSTOM_MERGE_INLINE_JS'],
    warning: 'Deprecated: "TAKT_PIECE_ARPEGGIO_CUSTOM_MERGE_INLINE_JS" is deprecated. Use "TAKT_WORKFLOW_ARPEGGIO_CUSTOM_MERGE_INLINE_JS" instead.',
  },
  {
    env: 'TAKT_PIECE_ARPEGGIO_CUSTOM_MERGE_FILES',
    path: 'piece_arpeggio.custom_merge_files',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_ARPEGGIO', 'TAKT_WORKFLOW_ARPEGGIO_CUSTOM_MERGE_FILES'],
    warning: 'Deprecated: "TAKT_PIECE_ARPEGGIO_CUSTOM_MERGE_FILES" is deprecated. Use "TAKT_WORKFLOW_ARPEGGIO_CUSTOM_MERGE_FILES" instead.',
  },
  {
    env: 'TAKT_PIECE_MCP_SERVERS',
    path: 'piece_mcp_servers',
    type: 'json',
    blockedBy: ['TAKT_WORKFLOW_MCP_SERVERS'],
    warning: 'Deprecated: "TAKT_PIECE_MCP_SERVERS" is deprecated. Use "TAKT_WORKFLOW_MCP_SERVERS" instead.',
  },
  {
    env: 'TAKT_PIECE_MCP_SERVERS_STDIO',
    path: 'piece_mcp_servers.stdio',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_MCP_SERVERS', 'TAKT_WORKFLOW_MCP_SERVERS_STDIO'],
    warning: 'Deprecated: "TAKT_PIECE_MCP_SERVERS_STDIO" is deprecated. Use "TAKT_WORKFLOW_MCP_SERVERS_STDIO" instead.',
  },
  {
    env: 'TAKT_PIECE_MCP_SERVERS_SSE',
    path: 'piece_mcp_servers.sse',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_MCP_SERVERS', 'TAKT_WORKFLOW_MCP_SERVERS_SSE'],
    warning: 'Deprecated: "TAKT_PIECE_MCP_SERVERS_SSE" is deprecated. Use "TAKT_WORKFLOW_MCP_SERVERS_SSE" instead.',
  },
  {
    env: 'TAKT_PIECE_MCP_SERVERS_HTTP',
    path: 'piece_mcp_servers.http',
    type: 'boolean',
    blockedBy: ['TAKT_WORKFLOW_MCP_SERVERS', 'TAKT_WORKFLOW_MCP_SERVERS_HTTP'],
    warning: 'Deprecated: "TAKT_PIECE_MCP_SERVERS_HTTP" is deprecated. Use "TAKT_WORKFLOW_MCP_SERVERS_HTTP" instead.',
  },
  {
    env: 'TAKT_NOTIFICATION_SOUND_EVENTS_PIECE_COMPLETE',
    path: 'notification_sound_events.piece_complete',
    type: 'boolean',
    blockedBy: ['TAKT_NOTIFICATION_SOUND_EVENTS', 'TAKT_NOTIFICATION_SOUND_EVENTS_WORKFLOW_COMPLETE'],
    warning: 'Deprecated: "TAKT_NOTIFICATION_SOUND_EVENTS_PIECE_COMPLETE" is deprecated. Use "TAKT_NOTIFICATION_SOUND_EVENTS_WORKFLOW_COMPLETE" instead.',
  },
  {
    env: 'TAKT_NOTIFICATION_SOUND_EVENTS_PIECE_ABORT',
    path: 'notification_sound_events.piece_abort',
    type: 'boolean',
    blockedBy: ['TAKT_NOTIFICATION_SOUND_EVENTS', 'TAKT_NOTIFICATION_SOUND_EVENTS_WORKFLOW_ABORT'],
    warning: 'Deprecated: "TAKT_NOTIFICATION_SOUND_EVENTS_PIECE_ABORT" is deprecated. Use "TAKT_NOTIFICATION_SOUND_EVENTS_WORKFLOW_ABORT" instead.',
  },
  {
    env: 'TAKT_LOG_LEVEL',
    path: 'logging.level',
    type: 'string',
    blockedBy: ['TAKT_LOGGING', 'TAKT_LOGGING_LEVEL'],
    warning: 'Deprecated: "TAKT_LOG_LEVEL" is deprecated. Use "TAKT_LOGGING_LEVEL" instead.',
  },
  {
    env: 'TAKT_OBSERVABILITY_PROVIDER_EVENTS',
    path: 'logging.provider_events',
    type: 'boolean',
    blockedBy: ['TAKT_LOGGING', 'TAKT_LOGGING_PROVIDER_EVENTS'],
    warning: 'Deprecated: "TAKT_OBSERVABILITY_PROVIDER_EVENTS" is deprecated. Use "TAKT_LOGGING_PROVIDER_EVENTS" instead.',
  },
];
