import { PROVIDER_OPTIONS_ENV_SPECS } from '../providerOptionsContract.js';
import type { EnvSpec } from './config-env-shared.js';

export const PROJECT_ENV_SPECS: readonly EnvSpec[] = [
  { path: 'provider', type: 'string' },
  { path: 'model', type: 'string' },
  { path: 'concurrency', type: 'number' },
  { path: 'pipeline', type: 'json' },
  { path: 'pipeline.default_branch_prefix', type: 'string' },
  { path: 'pipeline.commit_message_template', type: 'string' },
  { path: 'pipeline.pr_body_template', type: 'string' },
  { path: 'persona_providers', type: 'json' },
  { path: 'branch_name_strategy', type: 'string' },
  { path: 'minimal_output', type: 'boolean' },
  { path: 'task_poll_interval_ms', type: 'number' },
  { path: 'interactive_preview_steps', type: 'number' },
  { path: 'sync_project_local_takt_on_retry', type: 'boolean' },
  { path: 'analytics', type: 'json' },
  { path: 'analytics.enabled', type: 'boolean' },
  { path: 'analytics.events_path', type: 'string' },
  { path: 'analytics.retention_days', type: 'number' },
  ...PROVIDER_OPTIONS_ENV_SPECS,
  { path: 'provider_profiles', type: 'json' },
  { path: 'base_branch', type: 'string' },
  { path: 'workflow_runtime_prepare', type: 'json' },
  { path: 'workflow_runtime_prepare.custom_scripts', type: 'boolean' },
  { path: 'workflow_arpeggio', type: 'json' },
  { path: 'workflow_arpeggio.custom_data_source_modules', type: 'boolean' },
  { path: 'workflow_arpeggio.custom_merge_inline_js', type: 'boolean' },
  { path: 'workflow_arpeggio.custom_merge_files', type: 'boolean' },
  { path: 'sync_conflict_resolver', type: 'json' },
  { path: 'sync_conflict_resolver.auto_approve_tools', type: 'boolean' },
  { path: 'workflow_mcp_servers', type: 'json' },
  { path: 'workflow_mcp_servers.stdio', type: 'boolean' },
  { path: 'workflow_mcp_servers.sse', type: 'boolean' },
  { path: 'workflow_mcp_servers.http', type: 'boolean' },
];
