import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type { StructuredCaller } from '../agents/structured-caller.js';
import type { RunAgentOptions } from '../agents/runner.js';
import type { AgentResponse, WorkflowConfig } from '../core/models/index.js';
import { WorkflowEngine } from '../core/workflow/index.js';
import { detectRuleIndex } from '../shared/utils/ruleIndex.js';
import type { StreamEvent } from '../shared/types/provider.js';

vi.mock('../agents/runner.js', () => ({
  runAgent: vi.fn(),
}));

import { runAgent } from '../agents/runner.js';

function response(overrides: Partial<AgentResponse>): AgentResponse {
  return {
    persona: 'coder',
    status: 'done',
    content: 'done',
    timestamp: new Date('2026-06-28T00:00:00Z'),
    ...overrides,
  };
}

function workflowConfig(): WorkflowConfig {
  return {
    name: 'report-fallback-it',
    maxSteps: 3,
    initialStep: 'implement',
    steps: [{
      name: 'implement',
      persona: 'coder',
      personaDisplayName: 'Coder',
      instruction: 'Implement the task',
      passPreviousResponse: false,
      outputContracts: [{ name: 'review.md' }],
      rules: [{ condition: 'approved', next: 'COMPLETE' }],
    }],
  };
}

function queueAttempt(result: AgentResponse, streamEvents: StreamEvent[] = []): void {
  vi.mocked(runAgent).mockImplementationOnce(async (persona, task, options) => {
    options?.onPromptResolved?.({
      systemPrompt: typeof persona === 'string' ? persona : '',
      userInstruction: task,
    });

    for (const event of streamEvents) {
      options?.onStream?.(event);
    }

    return result;
  });
}

describe('WorkflowEngine report fallback integration', () => {
  let tmpRoot: string;

  beforeEach(() => {
    tmpRoot = mkdtempSync(join(tmpdir(), 'takt-report-fallback-it-'));
    vi.mocked(runAgent).mockReset();
  });

  afterEach(() => {
    if (existsSync(tmpRoot)) {
      rmSync(tmpRoot, { recursive: true, force: true });
    }
  });

  it('should pass configured fallback provider to the final report runAgent call and write the report', async () => {
    queueAttempt(response({
      content: '[IMPLEMENT:1]\nPhase 1 output',
      sessionId: 'opencode-session-1',
    }));
    queueAttempt(response({ content: '# Report\nfirst attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-1', tool: 'read', input: {} },
    }]);
    queueAttempt(response({ content: '# Report\nretry attempt' }), [{
      type: 'tool_use',
      data: { id: 'tool-2', tool: 'bash', input: {} },
    }]);
    queueAttempt(response({
      content: '# Report\nGenerated by fallback provider',
      sessionId: 'codex-fallback-session',
    }));
    const structuredCaller: StructuredCaller = {
      judgeStatus: vi.fn().mockResolvedValue({ ruleIndex: 0, method: 'structured_output' }),
      evaluateCondition: vi.fn(),
      decomposeTask: vi.fn(),
      requestMoreParts: vi.fn(),
    };

    const engine = new WorkflowEngine(workflowConfig(), tmpRoot, 'Task: implement fallback', {
      projectCwd: tmpRoot,
      provider: 'opencode',
      model: 'opencode/qwen3-coder-next',
      reportFallbackProvider: {
        provider: 'codex',
        model: 'gpt-5-report',
      },
      reportDirName: 'report-fallback-it',
      detectRuleIndex,
      structuredCaller,
    });

    const state = await engine.run();

    expect(state.status).toBe('completed');
    expect(readFileSync(join(tmpRoot, '.takt', 'runs', 'report-fallback-it', 'reports', 'review.md'), 'utf-8'))
      .toBe('# Report\nGenerated by fallback provider');
    expect(runAgent).toHaveBeenCalledTimes(4);
    expect(structuredCaller.judgeStatus).toHaveBeenCalledTimes(1);
    expect(structuredCaller.judgeStatus).toHaveBeenCalledWith(
      expect.any(String),
      expect.any(String),
      [{ condition: 'approved', next: 'COMPLETE' }],
      expect.objectContaining({
        stepName: 'implement',
        resolvedProvider: 'opencode',
        resolvedModel: 'opencode/qwen3-coder-next',
      }),
    );

    const fallbackOptions = vi.mocked(runAgent).mock.calls[3]?.[2] as RunAgentOptions;
    expect(fallbackOptions).toEqual(expect.objectContaining({
      resolvedProvider: 'codex',
      resolvedModel: 'gpt-5-report',
      permissionMode: 'readonly',
      allowedTools: [],
      sessionId: undefined,
    }));
  });
});
