/**
 * codex 対策#4（typed evidence protocol + verbatimExcerpt 機械照合 +
 * 二系統台帳 + gate 分離）の決定的 red/green fixture。
 *
 * 実 ledger の架空指摘7件（takt-bench v3-r4 run
 * 20260712-073441-pr-task-attachments-takt-add-p の
 * reviewers:2:ai-antipattern-review が返した finding-1〜finding-7）を、
 * 実際に生成された raw output のまま（読み取りのみで取得。この repo には
 * 一切書き込まない）フィクスチャとして固定する。
 *
 * gemma4:31b は ai-antipattern.md ポリシーの章見出し7つ（幻覚API/過剰実装/
 * デッドコード/フォールバック濫用/スコープクリープ/パターン不一致/後方互換）を
 * family_tag として丸暗記し、存在しないファイルへ1件ずつ割り当てた架空指摘を
 * 生成した（コードを読まずポリシー一覧を吐いた）。7件中6件（finding-1〜6）は
 * 存在しないファイルを指し、1件（finding-7、src/shared/constants.ts:20）は
 * 実在するパスを指すが引用内容は無関係（真の欠陥ではない）— 経路の実在性だけを
 * 見る旧チェックはこの1件を素通りさせていた。
 *
 * #4 前（red）: 6件は invalid-location-evidence provisional として product gate
 * を無条件に塞ぎ、1件（finding-7）は決定的検証なしで通常の open finding に昇格する。
 * #4 後（green）: 7件全てが reviewer anomaly（review-integrity 側の二系統台帳）へ
 * 隔離され、product finding は1件も作られず、product gate（findings.open.count /
 * findings.provisional.count）は塞がれない。
 *
 * このテストは #4 実装前後の両方でこのファイルのまま実行できる（RED は
 * 実装直前に stash して確認済み — 実装後は必ず GREEN であることを固定する）。
 */
import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import type { AgentResponse, WorkflowStep } from '../core/models/types.js';
import type { FindingLedger } from '../core/workflow/findings/types.js';
import { runFindingManagerForStep, type FindingManagerSubStepResult } from '../core/workflow/findings/manager-runner.js';
import type { FindingLedgerStore } from '../core/workflow/findings/store.js';
import { buildFindingsRuleContext as buildFindingsRuleContextWithCwd } from '../core/workflow/findings/context.js';
import { initializeGitFixture } from './helpers/git-fixture.js';

vi.mock('../agents/agent-usecases.js', () => ({
  executeAgent: vi.fn(),
}));

const { executeAgent } = await import('../agents/agent-usecases.js');
const executeAgentMock = vi.mocked(executeAgent);

function buildFindingsRuleContext(ledger: FindingLedger) {
  return buildFindingsRuleContextWithCwd(ledger, process.cwd());
}

beforeEach(() => {
  executeAgentMock.mockReset();
});

// ---------------------------------------------------------------------------
// fixture cwd: 実 v3-r4 run と同じ実在/不在パターンを再現する（hermetic —
// 実 takt リポジトリの現在の内容や行数の変化に依存しない）。
// ---------------------------------------------------------------------------
const FIXTURE_CWD = mkdtempSync(join(tmpdir(), 'takt-evidence-protocol-fixture-'));
function writeFixtureFile(relativePath: string, lineCount: number): void {
  const fullPath = join(FIXTURE_CWD, relativePath);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, `${Array.from({ length: lineCount }, (_, index) => `// unrelated line ${index + 1}`).join('\n')}\n`);
}
// finding-7 の claim（src/shared/constants.ts:20, "legacy mapping" 云々）と
// 無関係な内容の実在ファイル — 実 v3-r4 実測どおり「path は実在するが引用内容は
// 架空」を再現する。20行を超える内容にして line 20 を範囲内にする。
writeFixtureFile('src/shared/constants.ts', 29);
initializeGitFixture(FIXTURE_CWD, ['src/shared/constants.ts']);
// finding-1〜6 が指すパスは意図的に作らない（実際に存在しない）。

afterAll(() => {
  rmSync(FIXTURE_CWD, { recursive: true, force: true });
});

/**
 * 実 v3-r4 run（20260712-073441-pr-task-attachments-takt-add-p、
 * reviewers ステップの2回目実行、ai-antipattern-review）の raw output を
 * そのまま埋め込む。rawFindingId はエンジンの namespacedRawFindingId が
 * 付与する前の、reviewer が実際に返したローカル id（"finding-N"）。
 * このデータは takt-bench リポジトリ（読み取りのみ、書き込みなし）から
 * 1回だけ採取した凍結フィクスチャであり、以後 takt-bench には一切アクセスしない。
 */
const V3R4_AI_ANTIPATTERN_REVIEW_2ND_RAW_FINDINGS: Array<Record<string, unknown>> = [
  {
    rawFindingId: 'finding-1',
    familyTag: 'ai-hallucination',
    severity: 'high',
    title: 'Potential use of non-existent API method',
    location: 'src/core/workflowExecutor.ts:45',
    description: "The generated code calls `provider.executeWithRetryAsync()`, but the provider interface only defines `executeWithRetry()`. This appears to be an AI hallucination of a common naming pattern.",
    suggestion: 'Change `executeWithRetryAsync()` to `executeWithRetry()`.',
    relation: 'new',
  },
  {
    rawFindingId: 'finding-2',
    familyTag: 'over-engineering',
    severity: 'low',
    title: 'Excessive abstraction for simple logic',
    location: 'src/shared/utils/stringHelper.ts:12',
    description: 'The AI introduced a complex Strategy pattern for a string transformation that is only used in one place, increasing cognitive load without providing actual extensibility.',
    suggestion: 'Inline the logic into a simple utility function.',
    relation: 'new',
  },
  {
    rawFindingId: 'finding-3',
    familyTag: 'dead-code',
    severity: 'medium',
    title: 'Unused helper method generated by AI',
    location: 'src/features/config/configLoader.ts:88',
    description: 'The method `validateLegacyConfigFormat` was generated but is never called within the codebase, likely a leftover from a previous prompt iteration.',
    suggestion: 'Remove the unused method.',
    relation: 'new',
  },
  {
    rawFindingId: 'finding-4',
    familyTag: 'fallback-abuse',
    severity: 'medium',
    title: 'Over-reliance on default arguments masking missing data',
    location: 'src/app/cli/commands/setup.ts:30',
    description: 'The AI added default empty strings to almost all parameters in the setup command, which hides configuration errors that should be explicitly reported to the user.',
    suggestion: 'Remove defaults for required configuration fields and implement proper validation errors.',
    relation: 'new',
  },
  {
    rawFindingId: 'finding-5',
    familyTag: 'scope-creep',
    severity: 'low',
    title: 'Implementation of unrequested feature',
    location: 'src/core/logging/logger.ts:110',
    description: 'The AI implemented a remote syslog exporter that was not requested in the requirements, adding unnecessary dependencies.',
    suggestion: 'Remove the syslog exporter logic.',
    relation: 'new',
  },
  {
    rawFindingId: 'finding-6',
    familyTag: 'pattern-mismatch',
    severity: 'medium',
    title: 'Inconsistent error handling pattern',
    location: 'src/features/api/client.ts:55',
    description: 'The AI used a try-catch block that swallows errors and returns null, whereas the rest of the project uses a Result type for explicit error handling.',
    suggestion: 'Refactor the method to return a `Result<T, E>` type.',
    relation: 'new',
  },
  {
    rawFindingId: 'finding-7',
    familyTag: 'legacy-bloat',
    severity: 'low',
    title: 'Unnecessary backward compatibility logic',
    location: 'src/shared/constants.ts:20',
    description: 'The AI added a mapping for a version of the config file that was deprecated three versions ago and is no longer supported by the system.',
    suggestion: 'Remove the legacy mapping logic.',
    relation: 'new',
  },
];

function makeHarness(initialLedger: FindingLedger): {
  currentLedger: () => FindingLedger;
  run: () => ReturnType<typeof runFindingManagerForStep>;
} {
  let ledgerState = initialLedger;
  const reservations = new Set<string>();
  const ledgerStore: FindingLedgerStore = {
    workflowName: 'peer-review',
    loadLedger: () => ledgerState,
    saveLedger: (next) => { ledgerState = next; },
    updateLedger: (mutator) => {
      const mutation = mutator(ledgerState);
      ledgerState = mutation.ledger;
      return Promise.resolve(mutation);
    },
    claimAdjudicationReservation: (token) => {
      if (reservations.has(token)) return false;
      reservations.add(token);
      return true;
    },
    releaseAdjudicationReservation: (token) => { reservations.delete(token); },
    createRunCopy: () => '/tmp/ledger-copy.json',
    saveRawFindings: () => '/tmp/raw-findings.json',
    saveManagerValidationReport: () => '/tmp/manager-report.json',
    saveConflictAdjudicationReport: () => '/tmp/adjudication-report.json',
    saveNeedsAdjudicationReport: () => '/tmp/needs-adjudication.json',
  };
  const optionsBuilder = {
    buildAgentOptions: () => ({}),
    resolveStepProviderModel: () => ({ provider: 'opencode', model: 'gemma4:31b' }),
  };
  const stepExecutor = {
    buildPhase1Instruction: (instruction: string) => instruction,
    recordSynthesizedAgentUsage: () => {},
    normalizeStructuredOutput: (_step: WorkflowStep, response: AgentResponse) => response,
  };
  const parentStep: WorkflowStep = { kind: 'agent', name: 'reviewers', persona: 'reviewer', edit: false } as WorkflowStep;
  const contract = {
    ledgerPath: '.takt/findings/ledger.json',
    rawFindingsPath: '.takt/findings/raw',
    manager: {
      persona: 'findings-manager',
      instruction: 'Reconcile findings.',
      outputContract: 'Return JSON.',
    },
  };
  return {
    currentLedger: () => ledgerState,
    run: () => {
      const subResults: FindingManagerSubStepResult[] = [{
        subStep: { kind: 'agent', name: 'ai-antipattern-review', persona: 'ai-antipattern-reviewer', edit: false } as WorkflowStep,
        response: {
          status: 'done',
          content: '',
          structuredOutput: { rawFindings: V3R4_AI_ANTIPATTERN_REVIEW_2ND_RAW_FINDINGS },
        } as unknown as AgentResponse,
      }];
      return runFindingManagerForStep({
        contract: contract as never,
        ledgerStore,
        optionsBuilder: optionsBuilder as never,
        stepExecutor: stepExecutor as never,
        cwd: FIXTURE_CWD,
        parentStep,
        stepIteration: 2,
        subResults,
        workflowName: 'peer-review',
        runId: '20260712-073441-pr-task-attachments-takt-add-p',
        callNamespace: '',
        timestamp: '2026-07-12T09:05:19.675Z',
      });
    },
  };
}

describe('codex 対策#4 red/green fixture: v3-r4 実測の gemma 架空指摘7件（ai-antipattern-review 2巡目）', () => {
  it('GREEN: 7件全てが reviewer anomaly へ隔離され、product finding は1件も作られず、product gate は塞がれない', async () => {
    const harness = makeHarness({
      version: 1, workflowName: 'peer-review', nextId: 1, updatedAt: '2026-07-12T00:00:00.000Z',
      findings: [], rawFindings: [], conflicts: [],
    });

    const result = await harness.run();

    // 決定的検証だけで着地する — manager（LLM）は一切呼ばれない。
    expect(executeAgentMock).not.toHaveBeenCalled();
    expect(result.status).toBe('updated');

    const ledger = harness.currentLedger();
    // product finding は1件も作られない（7件全てが anomaly へ隔離された）。
    expect(ledger.findings).toHaveLength(0);

    const context = buildFindingsRuleContext(ledger);
    // product gate（COMPLETE 判定が直接参照する2つの count）は塞がれない。
    expect(context.open.count).toBe(0);
    expect(context.provisional.count).toBe(0);
    // review-integrity 側には全件残る（観測は消えない）。
    expect(context.reviewerAnomalies.count).toBe(7);

    // 二系統台帳の実体を直接検証する: 6件は「path が存在しない」引用不一致、
    // 1件（finding-7 相当）は「path は実在するが引用が無い（verbatimExcerpt 欠損）」
    // ため、こちらも quote-mismatch として隔離される — 経路の実在性だけを見る
    // 旧チェックが見逃していた欠陥（v3-r4 実測 F-0009）を新チェックは塞ぐ。
    const anomalies = ledger.reviewerAnomalies ?? [];
    expect(anomalies).toHaveLength(7);
    for (const anomaly of anomalies) {
      expect(anomaly.kind).toBe('quote-mismatch');
      expect(anomaly.promotedFindingId).toBeUndefined();
      expect(anomaly.occurrences).toBe(1);
    }
    const titles = anomalies.map((anomaly) => anomaly.title).sort();
    expect(titles).toEqual([
      'Excessive abstraction for simple logic',
      'Implementation of unrequested feature',
      'Inconsistent error handling pattern',
      'Over-reliance on default arguments masking missing data',
      'Potential use of non-existent API method',
      'Unnecessary backward compatibility logic',
      'Unused helper method generated by AI',
    ].sort());

    // finding-7（実在パス、引用なし）も他の6件と同じ扱いになっていることを
    // 明示的に確認する — これが「path 実在チェックだけでは不十分」の直接証拠。
    const finding7Anomaly = anomalies.find((anomaly) => anomaly.title === 'Unnecessary backward compatibility logic');
    expect(finding7Anomaly?.claimedLocation).toBe('src/shared/constants.ts:20');
  });

  it('reviewer anomaly は critical-path の安全不変条件を満たす: invalidated/resolved/waived な状態を持たず、findings 配列を一切変更しない', async () => {
    const seedFinding = {
      id: 'F-0001',
      status: 'open' as const,
      lifecycle: 'new' as const,
      severity: 'medium' as const,
      title: 'A genuine, unrelated pre-existing finding',
      location: 'src/shared/constants.ts:5',
      description: 'Pre-existing finding untouched by this round.',
      reviewers: ['arch-review'],
      rawFindingIds: ['raw-seed'],
      firstSeen: { runId: 'run-0', stepName: 'reviewers', timestamp: '2026-07-01T00:00:00.000Z' },
      lastSeen: { runId: 'run-0', stepName: 'reviewers', timestamp: '2026-07-01T00:00:00.000Z' },
      revision: 1,
    };
    const harness = makeHarness({
      version: 1, workflowName: 'peer-review', nextId: 2, updatedAt: '2026-07-12T00:00:00.000Z',
      findings: [seedFinding],
      rawFindings: [{
        rawFindingId: 'raw-seed',
        stepName: 'reviewers',
        reviewer: 'arch-review',
        familyTag: 'bug',
        severity: 'medium',
        title: 'A genuine, unrelated pre-existing finding',
        location: 'src/shared/constants.ts:5',
        description: 'Pre-existing finding untouched by this round.',
      }],
      conflicts: [],
    });

    await harness.run();

    const ledger = harness.currentLedger();
    // 既存 finding は状態・revision とも一切変更されない（別配列なので触りようがない）。
    const preserved = ledger.findings.find((finding) => finding.id === 'F-0001');
    expect(preserved).toEqual(seedFinding);

    // ReviewerAnomalyEntry には status/lifecycle/waivers フィールドが型として
    // 存在しない（invalidated/resolved/waived として扱えない）。
    for (const anomaly of ledger.reviewerAnomalies ?? []) {
      expect(anomaly).not.toHaveProperty('status');
      expect(anomaly).not.toHaveProperty('lifecycle');
      expect(anomaly).not.toHaveProperty('waivers');
    }
  });
});
